server:
  port: 8040
spring:
  application:
    name: infra-gateway
eureka:
  client:
    service-url:
      defaultZone: http://admin:q1w2e3r4t5@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    app-user: /user/**
    app-order: /order/**
  prefix: /api
  ignore-security-headers: false
#  InfraPreZuulFilter:
#    pre:
#      disable: true